import type { PublicBanner, PublicNews } from "./content";

export const summerBanners: PublicBanner[] = [
  {
    bannerId: -101,
    title: "Mùa hè mát lạnh cùng CoffeeGo",
    subtitle: "Cà phê sữa đá, cold brew và trà trái cây được pha mới mỗi ngày cho những buổi nắng rực rỡ.",
    imgUrl: "/customer-assets/summer-iced-coffee-banner.png",
    linkUrl: "/products",
    position: 1,
  },
  {
    bannerId: -102,
    title: "Bộ sưu tập giải nhiệt tháng 6",
    subtitle: "Thử ngay cold brew, trà cam đào và bánh ngọt dùng kèm trong khung giờ trưa hè.",
    imgUrl: "/customer-assets/summer-fruit-tea-cold-brew-banner.png",
    linkUrl: "/news/bo-suu-tap-giai-nhiet-thang-6",
    position: 2,
  },
  {
    bannerId: -103,
    title: "Combo hè cho nhóm bạn",
    subtitle: "Tiết kiệm hơn khi gọi combo nước đá mát lạnh kèm bánh nướng tại cửa hàng hoặc mang đi.",
    imgUrl: "/customer-assets/summer-combo-banner.png",
    linkUrl: "/products",
    position: 3,
  },
];

export const summerNews: PublicNews[] = [
  {
    newsId: -201,
    slug: "bo-suu-tap-giai-nhiet-thang-6",
    title: "CoffeeGo ra mắt bộ sưu tập giải nhiệt tháng 6",
    category: "Sản phẩm mùa hè",
    excerpt: "Từ ngày 04/06/2026, CoffeeGo giới thiệu nhóm đồ uống đá mới gồm cà phê sữa đá đậm vị, cold brew thanh nhẹ và trà trái cây tươi mát.",
    image: "/customer-assets/summer-fruit-tea-cold-brew-banner.png",
    date: "04/06/2026",
    sortDate: "2026-06-04",
    readTime: 3,
    body: [
      "Từ ngày 04/06/2026, CoffeeGo làm mới menu mùa hè bằng các món uống nhiều đá, vị sáng và dễ dùng trong thời tiết nóng.",
      "Bộ sưu tập tập trung vào ba nhóm hương: cà phê đậm vị, cold brew thanh sạch và trà trái cây có độ chua ngọt cân bằng.",
      "Các món được gợi ý dùng trong khung giờ trưa và chiều, khi khách cần một ly nước mát nhưng vẫn giữ tinh thần tỉnh táo cho ngày làm việc.",
    ],
  },
  {
    newsId: -202,
    slug: "combo-he-cho-nhom-ban",
    title: "Combo hè cho nhóm bạn: mát nhanh, tiết kiệm hơn",
    category: "Combo",
    excerpt: "CoffeeGo bổ sung các combo đồ uống đá và bánh nướng để khách đi nhóm có thêm lựa chọn gọn, nhanh và tiết kiệm.",
    image: "/customer-assets/summer-combo-banner.png",
    date: "02/06/2026",
    sortDate: "2026-06-02",
    readTime: 3,
    body: [
      "Từ ngày 02/06/2026, các cửa hàng CoffeeGo bắt đầu đẩy mạnh combo mùa hè dành cho nhóm hai đến bốn người.",
      "Mỗi combo kết hợp đồ uống đá, trà trái cây hoặc cold brew với bánh nướng để khách dễ chọn khi cần một phần dùng chung.",
      "Các combo đang bán sẽ được hiển thị trong trang menu khách hàng để người dùng nhìn thấy ngay trước khi đặt món.",
    ],
  },
  {
    newsId: -203,
    slug: "ca-phe-sua-da-mua-he",
    title: "Cà phê sữa đá mùa hè: đậm vị nhưng vẫn nhẹ nhàng",
    category: "Văn hóa cà phê",
    excerpt: "Barista CoffeeGo điều chỉnh tỷ lệ đá, sữa và nền cà phê để ly cà phê sữa đá giữ được độ đậm sau khi tan đá.",
    image: "/customer-assets/summer-iced-coffee-banner.png",
    date: "30/05/2026",
    sortDate: "2026-05-30",
    readTime: 4,
    body: [
      "Cà phê sữa đá là món quen thuộc, nhưng mùa hè cần một tỷ lệ pha cân bằng hơn để ly không bị nhạt quá nhanh.",
      "CoffeeGo ưu tiên nền cà phê rang vừa, vị chocolate nhẹ và hậu ngọt để món uống vẫn rõ hương sau vài phút trong đá.",
      "Khách có thể chọn giảm sữa hoặc thêm shot nếu muốn ly đậm hơn trong những ngày nắng nóng.",
    ],
  },
  {
    newsId: -204,
    slug: "cold-brew-cam-vang",
    title: "Cold brew cam vàng trở lại trong menu tháng 5",
    category: "Sản phẩm mùa hè",
    excerpt: "Cold brew cam vàng kết hợp cà phê ủ lạnh với citrus tươi, phù hợp cho khách thích vị cà phê sáng và ít ngọt.",
    image: "photo-1461023058943-07fcbe16d735",
    date: "27/05/2026",
    sortDate: "2026-05-27",
    readTime: 3,
    body: [
      "Từ ngày 27/05/2026, cold brew cam vàng quay lại menu mùa hè tại CoffeeGo.",
      "Món uống có nền cà phê ủ lạnh trong nhiều giờ, kết hợp lớp citrus tươi để tạo cảm giác nhẹ và sạch vị.",
      "Đây là lựa chọn phù hợp cho khách muốn cà phê ít sữa, ít ngọt nhưng vẫn có điểm nhấn hương trái cây.",
    ],
  },
  {
    newsId: -205,
    slug: "uu-dai-trua-he-van-phong",
    title: "Ưu đãi trưa hè cho khách văn phòng",
    category: "Khuyến mãi",
    excerpt: "Trong khung 11:00-13:30 từ cuối tháng 5, CoffeeGo áp dụng ưu đãi theo combo cho khách đặt nhanh tại cửa hàng.",
    image: "photo-1495474472287-4d71bcdd2085",
    date: "24/05/2026",
    sortDate: "2026-05-24",
    readTime: 2,
    body: [
      "Từ ngày 24/05/2026, CoffeeGo triển khai ưu đãi trưa hè tại các cửa hàng có lượng khách văn phòng cao.",
      "Khách có thể chọn combo đồ uống đá kèm bánh nướng, phù hợp cho bữa nhẹ hoặc giờ nghỉ giữa ngày.",
      "Chương trình được thiết kế để rút ngắn thời gian chọn món và giúp khách nhận đồ nhanh hơn trong khung giờ đông.",
    ],
  },
  {
    newsId: -206,
    slug: "tra-dao-cam-sa-mua-nang",
    title: "Trà đào cam sả được làm mới cho mùa nắng",
    category: "Sản phẩm mùa hè",
    excerpt: "Công thức trà đào cam sả được cân lại độ ngọt và hương sả để dễ uống hơn trong những ngày oi nóng.",
    image: "photo-1556679343-c7306c1976bc",
    date: "21/05/2026",
    sortDate: "2026-05-21",
    readTime: 3,
    body: [
      "Từ ngày 21/05/2026, trà đào cam sả tại CoffeeGo được tinh chỉnh để hợp hơn với mùa nóng.",
      "Độ ngọt được giảm nhẹ, phần hương sả được giữ vừa đủ để món uống có cảm giác tươi mà không át vị đào.",
      "Khách thích vị thanh có thể chọn mức đường thấp và thêm đá để ly uống giữ độ mát lâu hơn.",
    ],
  },
  {
    newsId: -207,
    slug: "barista-goi-y-do-uong-thang-5",
    title: "Barista gợi ý 5 món uống đáng thử cuối tháng 5",
    category: "Gợi ý menu",
    excerpt: "Các barista CoffeeGo chọn ra những món dễ uống nhất cho thời tiết chuyển hè: cold brew, bạc xỉu đá và trà trái cây.",
    image: "photo-1517701604599-bb29b565090c",
    date: "18/05/2026",
    sortDate: "2026-05-18",
    readTime: 4,
    body: [
      "Ngày 18/05/2026, đội barista CoffeeGo tổng hợp danh sách món uống nên thử khi thời tiết bắt đầu nóng hơn.",
      "Nhóm món được nhắc nhiều gồm bạc xỉu đá, cold brew, cà phê sữa đá và các dòng trà trái cây.",
      "Danh sách này cũng là cơ sở để trang menu khách hàng làm nổi bật nhóm bán chạy và sản phẩm mùa.",
    ],
  },
  {
    newsId: -208,
    slug: "khong-gian-mua-he-tai-coffeego",
    title: "Không gian mùa hè tại CoffeeGo: thêm xanh, thêm mát",
    category: "Cửa hàng",
    excerpt: "Một số cửa hàng CoffeeGo bổ sung cây xanh, ánh sáng dịu và khu vực ngồi gần cửa sổ để khách làm việc thoải mái hơn.",
    image: "photo-1554118811-1e0d58224f24",
    date: "15/05/2026",
    sortDate: "2026-05-15",
    readTime: 3,
    body: [
      "Từ giữa tháng 5/2026, CoffeeGo bắt đầu làm mới không gian tại một số cửa hàng theo tinh thần mùa hè.",
      "Các thay đổi tập trung vào cây xanh, ánh sáng dịu và khu vực ngồi có ổ cắm cho khách làm việc lâu hơn.",
      "Không gian mới đi cùng menu đồ uống đá để khách có trải nghiệm mát mẻ hơn khi ghé quán.",
    ],
  },
  {
    newsId: -209,
    slug: "banh-ngot-an-kem-ca-phe-da",
    title: "Bánh ngọt nào hợp nhất với cà phê đá?",
    category: "Gợi ý menu",
    excerpt: "Croissant bơ, muffin chocolate và bánh phô mai nhẹ vị là ba lựa chọn được CoffeeGo gợi ý khi dùng kèm cà phê đá.",
    image: "photo-1509440159596-0249088772ff",
    date: "10/05/2026",
    sortDate: "2026-05-10",
    readTime: 4,
    body: [
      "Ngày 10/05/2026, CoffeeGo giới thiệu gợi ý bánh dùng kèm các món cà phê đá trong mùa hè.",
      "Croissant bơ hợp với cà phê sữa đá, muffin chocolate hợp cold brew, còn bánh phô mai nhẹ vị hợp trà trái cây.",
      "Các cặp món này cũng được dùng để xây dựng combo trên trang menu khách hàng.",
    ],
  },
  {
    newsId: -210,
    slug: "lich-su-kien-thang-5-coffeego",
    title: "Lịch sự kiện tháng 5 tại CoffeeGo",
    category: "Sự kiện",
    excerpt: "CoffeeGo tổ chức các buổi thử vị cold brew và workshop pha cà phê đá vào cuối tuần trong tháng 5.",
    image: "photo-1521017432531-fbd92d768814",
    date: "05/05/2026",
    sortDate: "2026-05-05",
    readTime: 3,
    body: [
      "Từ ngày 05/05/2026, CoffeeGo mở lịch sự kiện tháng 5 với các buổi thử vị cold brew và workshop pha cà phê đá.",
      "Hoạt động diễn ra vào cuối tuần tại một số cửa hàng trung tâm, ưu tiên nhóm khách quan tâm đến cách pha và chọn hạt.",
      "Tin tức sự kiện sẽ tiếp tục được cập nhật trên trang Chuyện CoffeeGo trong suốt mùa hè.",
    ],
  },
];
