server.port=8081
spring.application.name=auth-service

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=10

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:*,http://127.0.0.1:*}
app.jwt.secret=${JWT_SECRET:coffee-chain-management-secret-key-change-me-in-production-2026}
app.jwt.access-token-minutes=${JWT_ACCESS_TOKEN_MINUTES:120}
app.jwt.refresh-token-days=${JWT_REFRESH_TOKEN_DAYS:7}
app.notification-service.url=${NOTIFICATION_SERVICE_URL:http://localhost:8092}
app.seed.admin-email=${ADMIN_EMAIL:admin@coffee.local}
app.seed.admin-password=${ADMIN_PASSWORD:Admin}
app.admin.password-recovery-email=${ADMIN_PASSWORD_RECOVERY_EMAIL:userstest2212@gmail.com}
app.google.client-id=${GOOGLE_CLIENT_ID:745520980006-j9d5du8ds25e5h2u9fgm035na29423cf.apps.googleusercontent.com}

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
