package com.coffee.inventoryservice.config;

import org.springframework.boot.CommandLineRunner;
import org.springframework.core.Ordered;
import org.springframework.core.annotation.Order;
import org.springframework.jdbc.core.ConnectionCallback;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

@Component
@Order(Ordered.HIGHEST_PRECEDENCE)
public class InventorySchemaInitializer implements CommandLineRunner {

    private final JdbcTemplate jdbcTemplate;

    public InventorySchemaInitializer(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    @Override
    public void run(String... args) {
        DatabaseContext database = databaseContext();
        createRestockTables(database);
        addColumnIfMissing(database, "Ingredient", "topping_price", "BIGINT NULL");
        backfillToppingPrices(database);
    }

    private void createRestockTables(DatabaseContext database) {
        String idDefinition = database.isMySql()
                ? "BIGINT NOT NULL AUTO_INCREMENT"
                : "BIGINT GENERATED BY DEFAULT AS IDENTITY";

        createTableIfMissing(database, "Restock_request", """
                CREATE TABLE Restock_request (
                    request_id %s,
                    branch_id BIGINT NOT NULL,
                    employee_id BIGINT NOT NULL,
                    status VARCHAR(32) NOT NULL DEFAULT 'pending',
                    note TEXT NULL,
                    created_at TIMESTAMP NOT NULL,
                    updated_at TIMESTAMP NULL,
                    PRIMARY KEY (request_id)
                )
                """.formatted(idDefinition));
        createTableIfMissing(database, "Restock_request_detail", """
                CREATE TABLE Restock_request_detail (
                    request_detail_id %s,
                    request_id BIGINT NOT NULL,
                    ingredient_id BIGINT NOT NULL,
                    quantity DOUBLE PRECISION NOT NULL,
                    unit VARCHAR(64) NOT NULL,
                    current_quantity DOUBLE PRECISION NULL,
                    min_quantity DOUBLE PRECISION NULL,
                    PRIMARY KEY (request_detail_id)
                )
                """.formatted(idDefinition));
        createIndexIfMissing(database, "Restock_request", "idx_restock_request_branch_status", "branch_id, status");
        createIndexIfMissing(database, "Restock_request", "idx_restock_request_created_at", "created_at");
        createIndexIfMissing(database, "Restock_request_detail", "idx_restock_request_detail_request", "request_id");
        createIndexIfMissing(database, "Restock_request_detail", "idx_restock_request_detail_ingredient", "ingredient_id");
    }

    private void backfillToppingPrices(DatabaseContext database) {
        if (database.isMySql()) {
            jdbcTemplate.update("""
                    UPDATE Ingredient i
                    JOIN Ingredient_category c ON c.i_category_id = i.i_category_id
                    SET i.topping_price = CASE
                        WHEN LOWER(i.ingredient_name) LIKE '%kem cheese%'
                          OR LOWER(i.ingredient_name) LIKE '%cream cheese%'
                          OR LOWER(i.ingredient_name) LIKE '%foam%'
                          OR LOWER(i.ingredient_name) LIKE '%macchiato%' THEN 10000
                        WHEN LOWER(i.ingredient_name) LIKE '%pudding%'
                          OR LOWER(i.ingredient_name) LIKE '%flan%' THEN 8000
                        WHEN LOWER(i.ingredient_name) LIKE '%tran chau%'
                          OR LOWER(i.ingredient_name) LIKE '%boba%'
                          OR LOWER(i.ingredient_name) LIKE '%pearl%' THEN 7000
                        WHEN LOWER(i.ingredient_name) LIKE '%nha dam%'
                          OR LOWER(i.ingredient_name) LIKE '%aloe%'
                          OR LOWER(i.ingredient_name) LIKE '%duong den%'
                          OR LOWER(i.ingredient_name) LIKE '%caramel%' THEN 6000
                        ELSE 5000
                    END
                    WHERE LOWER(c.i_category_name) = 'topping'
                      AND i.topping_price IS NULL
                    """);
            return;
        }

        jdbcTemplate.update("""
                UPDATE Ingredient i
                SET topping_price = CASE
                    WHEN LOWER(i.ingredient_name) LIKE '%kem cheese%'
                      OR LOWER(i.ingredient_name) LIKE '%cream cheese%'
                      OR LOWER(i.ingredient_name) LIKE '%foam%'
                      OR LOWER(i.ingredient_name) LIKE '%macchiato%' THEN 10000
                    WHEN LOWER(i.ingredient_name) LIKE '%pudding%'
                      OR LOWER(i.ingredient_name) LIKE '%flan%' THEN 8000
                    WHEN LOWER(i.ingredient_name) LIKE '%tran chau%'
                      OR LOWER(i.ingredient_name) LIKE '%boba%'
                      OR LOWER(i.ingredient_name) LIKE '%pearl%' THEN 7000
                    WHEN LOWER(i.ingredient_name) LIKE '%nha dam%'
                      OR LOWER(i.ingredient_name) LIKE '%aloe%'
                      OR LOWER(i.ingredient_name) LIKE '%duong den%'
                      OR LOWER(i.ingredient_name) LIKE '%caramel%' THEN 6000
                    ELSE 5000
                END
                FROM Ingredient_category c
                WHERE LOWER(c.i_category_name) = 'topping'
                  AND c.i_category_id = i.i_category_id
                  AND i.topping_price IS NULL
                """);
    }

    private void addColumnIfMissing(DatabaseContext database, String tableName, String columnName, String definition) {
        Integer count = jdbcTemplate.queryForObject("""
                SELECT COUNT(*)
                FROM INFORMATION_SCHEMA.COLUMNS
                WHERE TABLE_SCHEMA = ?
                  AND LOWER(TABLE_NAME) = LOWER(?)
                  AND LOWER(COLUMN_NAME) = LOWER(?)
                """, Integer.class, database.schema(), tableName, columnName);
        if (count == null || count == 0) {
            jdbcTemplate.execute("ALTER TABLE " + tableName + " ADD COLUMN " + columnName + " " + definition);
        }
    }

    private void createTableIfMissing(DatabaseContext database, String tableName, String sql) {
        Integer count = jdbcTemplate.queryForObject("""
                SELECT COUNT(*)
                FROM INFORMATION_SCHEMA.TABLES
                WHERE TABLE_SCHEMA = ?
                  AND LOWER(TABLE_NAME) = LOWER(?)
                """, Integer.class, database.schema(), tableName);
        if (count == null || count == 0) {
            jdbcTemplate.execute(sql);
        }
    }

    private void createIndexIfMissing(DatabaseContext database, String tableName, String indexName, String columns) {
        Integer count;
        if (database.isMySql()) {
            count = jdbcTemplate.queryForObject("""
                    SELECT COUNT(*)
                    FROM INFORMATION_SCHEMA.STATISTICS
                    WHERE TABLE_SCHEMA = ?
                      AND LOWER(TABLE_NAME) = LOWER(?)
                      AND LOWER(INDEX_NAME) = LOWER(?)
                    """, Integer.class, database.schema(), tableName, indexName);
        } else {
            count = jdbcTemplate.queryForObject("""
                    SELECT COUNT(*)
                    FROM pg_indexes
                    WHERE schemaname = ?
                      AND LOWER(tablename) = LOWER(?)
                      AND LOWER(indexname) = LOWER(?)
                    """, Integer.class, database.schema(), tableName, indexName);
        }
        if (count == null || count == 0) {
            jdbcTemplate.execute("CREATE INDEX " + indexName + " ON " + tableName + " (" + columns + ")");
        }
    }

    private DatabaseContext databaseContext() {
        String productName = jdbcTemplate.execute((ConnectionCallback<String>) connection ->
                connection.getMetaData().getDatabaseProductName());
        DatabaseType type = productName != null && productName.toLowerCase().contains("mysql")
                ? DatabaseType.MYSQL
                : DatabaseType.POSTGRESQL;
        String schema = type == DatabaseType.MYSQL
                ? jdbcTemplate.queryForObject("SELECT DATABASE()", String.class)
                : jdbcTemplate.queryForObject("SELECT CURRENT_SCHEMA()", String.class);
        return new DatabaseContext(type, schema);
    }

    private enum DatabaseType {
        MYSQL,
        POSTGRESQL
    }

    private record DatabaseContext(DatabaseType type, String schema) {
        private boolean isMySql() {
            return type == DatabaseType.MYSQL;
        }
    }
}
